[package]
name = "teleground"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
rocket_dyn_templates = { version = "0.1.0", features = ["tera"] }
tera = "1.19.1"

[dev-dependencies]
rand = "0.8"
